server {
      listen 80;
      server_name www.tsukimi-yachiyo.top tsukimi-yachiyo.top yachiyo.owo.vin www.yachiyo.owo.vin yachiyo.redchenk.com
  www.yachiyocat.top yachiyocat.top;

      client_max_body_size 20M;
      root /var/www/yachiyo;
      index index.html;

      gzip on;
      gzip_vary on;
      gzip_min_length 1024;
      gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml+rss
  application/json application/javascript;

      location / {
          try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://211.101.234.16:8881;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          add_header Access-Control-Allow-Origin *;
      }

      location /file {
          proxy_pass http://211.101.237.141:8881;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          add_header Access-Control-Allow-Origin *;
      }

      location /ws {
          proxy_pass http://211.101.237.141:8881;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location /actuator {
          proxy_pass http://211.101.237.141:8881;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
          expires 1y;
          add_header Cache-Control "public, immutable";
      }
  }
